urban_energie_battery_in_hourly:
  name: urban energie battery in hourly
  min: 0
  max: 10000
  step: 1
  unit_of_measurement: kWh

urban_energie_battery_out_hourly:
  name: urban energie battery out hourly
  initial: 0
  min: -10000
  max: 0
  step: 1
  unit_of_measurement: kWh

urban_batterie_virtuelle_pointage:
  name: Urban Batterie Virtuelle Pointage Manuel
  min: 0
  max: 10000
  step: 1
  mode: box
  unit_of_measurement: kWh

urban_batterie_virtuelle_stock:
  name: Urban Batterie Virtuelle Stock
  min: 0
  max: 10000
  step: 1
  mode: box
  unit_of_measurement: kWh
