# SENSORS TEMPLATE
template:
  - sensor:
      - name: "Diff Énergie Restituée Veille - Avant-Veille"
        unit_of_measurement: "kWh"
        state: >
          {% set veille = states('input_number.energie_restituee_veille') | float(0) %}
          {% set avant_veille = states('input_number.energie_restituee_avant_veille') | float(0) %}
          {{ veille - avant_veille }}
          

      - name: "Batterie Virtuelle Sortie Horaire"
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total
        state: >
          {% set val = states('input_number.energie_battery_out_hourly') | float(0) %}
          {{ -1 * val }}
        
      - name: "Batterie Virtuelle Entrée Horaire"
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total
        state: "{{ states('input_number.energie_battery_in_hourly') | float(0) }}"