 
  - platform: template
    sensors:
      batterie_virtuelle_sortie_horaire:
        friendly_name: "Batterie Virtuelle Sortie Horaire"
        unit_of_measurement: "kWh"
        value_template: >
          {% set val = states('input_number.energie_battery_out_hourly') | float(0) %}
          {{ -1 * val }}
  
  - platform: template
    sensors:
      batterie_virtuelle_entree_horaire:
        friendly_name: "Batterie Virtuelle Entrée Horaire"
        unit_of_measurement: "kWh"
        value_template: "{{ states('input_number.energie_battery_in_hourly') | float(0) }}"
