- platform: integration
  source: sensor.puissance_import_enedis
  name: urban_energie_importee_enedis
  unit_prefix: k
  round: 3
  method: left
  unit_time: s

- platform: template
  sensors:
    urban_energie_restituee_au_reseau:
      device_class: energy
      friendly_name: Urban Énergie Restituée au Réseau
      unit_of_measurement: kWh
      value_template: '{{ states(''sensor.urban_energie_solaire_produite'') | float(0) - states(''sensor.urban_energie_consommee_totale'') | float(0) }}'
