DOMAIN = "ha-urbansolar-bv"
CONF_PRODUCTION_SENSOR = "source_energie_produite"
CONF_CONSOMMATION_SENSOR = "source_energie_consommee"
CONF_SOLAR_POWER_SENSOR = "solar_power_sensor"
CONF_TOTAL_POWER_CONSO_SENSOR = "total_power_conso_sensor"