alias: Gestion horaire batterie virtuelle
trigger:
  - platform: time_pattern
    hours: "*"
    minutes: "59"
    seconds: "45"
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.energie_restituee_au_reseau_hourly
            above: 0
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.energie_battery_in_hourly
            data:
              value: "{{ states('input_number.energie_battery_in_hourly') | float(0) + states('sensor.energie_restituee_au_reseau_hourly') | float(0) }}"
      - conditions:
          - condition: numeric_state
            entity_id: sensor.energie_restituee_au_reseau_hourly
            below: 0
          - condition: numeric_state
            entity_id: input_number.batterie_virtuelle_stock
            above: 0
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.energie_battery_out_hourly
            data:
              value: >-
                {% set stock = states('input_number.batterie_virtuelle_stock') | float(0) %}
                {% set consommation = (states('sensor.energie_restituee_au_reseau_hourly') | float(0)) | abs %}
                {% if consommation > stock %}
                  {{ stock }}
                {% else %}
                  {{ consommation }}
                {% endif %}
mode: single
