automation:
  # Mise à jour hebdomadaire (00h00)
  - id: '174508910456'
    alias: "Mettre à jour les valeurs de veille et avant-veille"
    trigger:
      platform: time
      at: "00:00:00"    # Changé pour 00h00 (plus logique)
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.energie_restituee_avant_veille
        data:
          value: "{{ states('input_number.energie_restituee_veille')|float }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.energie_restituee_veille
        data:
          value: "{{ states('sensor.energie_restituee_au_reseau')|float }}"

  # Mise à jour Batterie Virtuelle Stock
  - id: '174508910457'
    alias: "Mettre à jour Batterie Virtuelle Stock"
    trigger:
      platform: time
      at: "00:01:00"
    action:
      - variables:
          stock_actuel: "{{ states('input_number.batterie_virtuelle_stock')|float }}"
          pointage: "{{ states('input_number.batterie_virtuelle_pointage')|float }}"
          diff: "{{ states('sensor.diff_energie_restituee_veille_avant_veille')|float }}"
        service: input_number.set_value
        target: 
          entity_id: input_number.batterie_virtuelle_stock
        data:
          value: >-
            {%- if pointage != 0 -%}
              {{ pointage + diff|float }}
            {%- else -%}
              {{ stock_actuel + diff|float }}
            {%- endif -%}
      - service: input_number.set_value
        target:
          entity_id: input_number.batterie_virtuelle_pointage
        data:
          value: 0

  # Gestion batterie virtuelle par heure
  - id: '174508910473'
    alias: "Gestion horaire batterie virtuelle"
    trigger:
      platform: time_pattern
      hours: '*'
      minutes: '59'
      seconds: '50'
    action:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.energie_restituee_au_reseau_hourly
                above: 0
            sequence:
              - service: input_number.set_value
                target:
                  entity_id: input_number.energie_battery_in_hourly
                data:
                  value: "{{ (states('input_number.energie_battery_in_hourly')|float + states('sensor.energie_restituee_au_reseau_hourly')|float)|round }}"
          - conditions:
              - condition: numeric_state
                entity_id: sensor.energie_restituee_au_reseau_hourly
                below: 0
            sequence:
              - service: input_number.set_value
                target:
                  entity_id: input_number.energie_battery_out_hourly
                data:
                  value: "{{ (states('input_number.energie_battery_out_hourly')|float + states('sensor.energie_restituee_au_reseau_hourly')|float)|round }}"