# .github/workflows/combine.yml

name: Combine Files

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # permet de le lancer manuellement aussi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies (if needed)
        run: pip install --upgrade pip

      - name: Run combine script
        run: python generate_single_file.py

      - name: Commit combined file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add combined_output.txt
          git commit -m "Generate combined file" || echo "No changes to commit"
          git push
