name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Pack the open_meteo_solar_forecast dir as a zip and upload to the release
      - name: ZIP urbansolar_bv Dir
        run: |
          cd ${{ github.workspace }}/custom_components/urbansolar_battery
          zip urbansolar_bv.zip -r ./
          ls
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/urbansolar_battery/urbansolar_bv.zip
          asset_name: urbansolar_bv.zip
          tag: ${{ github.ref }}
          overwrite: true
